apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: latishmk/bank
      context: ../bank
      jib: {}
    - image: latishmk/customer
      context: ../customer
      jib: {}
    - image: latishmk/product
      context: ../product
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
